### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by thoongee** [the-jb/attention-is-all-you-need#2]
from torchtext.datasets.translation import WMT14, Multi30k
from torchtext.data import Field, BucketIterator
이 두 모듈이 import error가 뜨는데,
사용하신 torch, torchtext, cuda, cudnn 버전을 알 수 있을까요?

**Comment by the-jb** [comment]
안녕하세요. 제보 감사드립니다. 확인해보니, https://github.com/pytorch/text/pull/1646 에서 WMT14 원본링크가 깨져, 유지보수 차원에서 제거되었네요. 링크 문제여서 아마 이전 버젼의 라이브러리를 설치해도 제대로 데이터를 받지 못할 것으로 보여 코드 수정하여 반영하겠습니다 :)

**Comment by the-jb** [comment]
구현 완료하여 이슈 닫겠습니다. 혹시 문제 있을 경우 말씀주세요.

**Comment by thoongee** [comment]
빠른 리뷰 감사드립니다!
test.py 의 코드에서도 torchtext로부터 WMT14 데이터셋을 받아오는 부분이 있어 추가 변경이 필요하지 않은지, 궁금합니다
그리고 코드 실행시, gpu상에서 작동하는 것이 아닌 cpu에서 학습 및 추론을 진행하는 코드처럼 보이는데, 맞나요?

**Comment by the-jb** [comment]
@thoongee 네 말씀 감사합니다. `test.py` 도 수정이 필요한데, 데이터셋뿐만 아니라 tokenizer 를 저장하는 등의 작업을 구현해야 할 것으로 보여서, 따로 시간 여유가 생기면 진행하고자 합니다.
코드의 주 목적은 사실 모델 구조를 잡는 것이어서 학습은 그냥 전반적인 프로세스를 보여주는 용이지, 다양한 셋팅을 고려하지는 않았습니다. 학습 코드도 사용하시고자 하신다면, (단일 gpu 경우) 코드에 `.cuda()` 호출을 통해 어렵지 않게 수정하셔서 사용하실 수 있습니다. :) 다만 `max_seq_len` 이나 `batch_size` 로 인해 메모리가 부족할 수 있으니, 값 확인이 필요합니다.
